# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CMake on a single platform

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac. ubuntu-latest
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      # Build your program with the given configuration
      run: |
        mkdir ${{ github.workspace }}/build
        cd ${{ github.workspace }}/build
        cmake ..
        cmake --build .

    - name: Upload GitHub Actions artifact of vcpkg build
      uses: actions/upload-artifact@v2
      with:
        name: blsd_win
        path: ${{ github.workspace }}/build/
      

